# Generated by Django 4.1.2 on 2022-10-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_userprofile_agent_organisaton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organisaton',
            new_name='organisation',
        ),
    ]
